packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  better-sqlite3: true
  canvas: false
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  ssh2: false
  unrs-resolver: true
